name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '17']
        python: ['3.9', '3.10']
        gcloudsdk: ['382.0.0']
    env:
      DOCKER_TAG: "${{ matrix.python }}-${{ matrix.node }}-${{ matrix.gcloudsdk }}"
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
      with:
        context: .
        push: true
        tags: psongers/python-node-gcloudsdk:${{ env.DOCKER_TAG }}
        build-args: |
          "pythonversion=${{ matrix.python }}"
          "nodejsversion=${{ matrix.node }}"
          "gcloudsdkversion=${{ matrix.gcloudsdk }}"
