name: Build Docker Image

on:
  push:
    branches:
      - master
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['17']
        python: ['3.10']
        gcloudsdk: ['382.0.0']
    env:
      DOCKER_IMAGE_NAME: "psongers/python-node-gcloudsdk"
      DOCKER_TAG: "${{ matrix.python }}-${{ matrix.node }}-${{ matrix.gcloudsdk }}"
    steps:
    - uses: actions/checkout@v3
    - name: Build the image.
      id: build
      run: |
        docker build \
          --build-arg pythonversion=${{ matrix.python }} \
          --build-arg nodejsversion=${{ matrix.node }} \
          --build-arg gcloudsdkversion=${{ matrix.gcloudsdk }} \
          -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} \
          .
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: $DOCKER_IMAGE_NAME
    
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
